version: 2
updates:
  # Enable version updates for npm (which includes package-lock.json)
  - package-ecosystem: "npm"
    # Look for `package.json` and `package-lock.json` files in the `root` directory
    directory: "/"
    # Check for updates every month
    schedule:
      interval: "monthly"

